steps:
- name: node:22.13.1
  entrypoint: npm
  args: ["install"]
- name: node:22.13.1
  entrypoint: npm
  args: ["run", "build"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
artifacts:
    npmPackages:
    - repository: 'https://us-west1-npm.pkg.dev/thomas-personal-website/tgp'
      packagePath: '.'
timeout: "1600s"